# Importing pandas

In [1]:
import pandas as pd

# Opening a local csv file

In [2]:
df = pd.read_csv('placement.csv') #it  by default load comma separated value

# Opening a csv file from an url & / Server

In [3]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv" # change url only for other
headers = {"User-Agent":"Mozilla/5.0(Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers = headers)
data = (StringIO(req.text))

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

# Opening tsv file

In [4]:
dft = pd.read_csv('file.tsv' , sep="\t")
dft

          0    50  5  881250949
0         0   172  5  881250949
1         0   133  1  881250949
2       196   242  3  881250949
3       186   302  3  891717742
4        22   377  1  878887116
...     ...   ... ..        ...
99997   880   476  3  880175444
99998   716   204  5  879795543
99999   276  1090  1  874795795
100000   13   225  2  882399156
100001   12   203  3  879959583

[100002 rows x 4 columns]

# Giving columns names

In [5]:
df_t = pd.read_csv('file.tsv' , sep="\t",names=["Sno" , "Working_days","Monthly_Overtime","Salary"])
df_t

        Sno  Working_days  Monthly_Overtime     Salary
0         0            50                 5  881250949
1         0           172                 5  881250949
2         0           133                 1  881250949
3       196           242                 3  881250949
4       186           302                 3  891717742
...     ...           ...               ...        ...
99998   880           476                 3  880175444
99999   716           204                 5  879795543
100000  276          1090                 1  874795795
100001   13           225                 2  882399156
100002   12           203                 3  879959583

[100003 rows x 4 columns]

# index_col Parameter

In [6]:
df = pd.read_csv('placement.csv' , sep=",", index_col="iq")
df

       Unnamed: 0  cgpa  placement
iq
123.0           0   6.8          1
106.0           1   5.9          0
121.0           2   5.3          0
132.0           3   7.4          1
142.0           4   5.8          0
...           ...   ...        ...
200.0          95   4.3          0
42.0           96   4.4          0
182.0          97   6.7          1
103.0          98   6.3          1
113.0          99   6.2          1

[100 rows x 3 columns]

# Header parameter

In [7]:
tdf = pd.read_csv("Test.csv" )
tdf.head()

  Unnamed Unnamed2 Unnamed3   Unnamed4
0   index     cgpa       iq  placement
1       1      5.9      106          0
2       2      5.3      121          0
3       3      7.4      132          1
4       4      5.8      142          0

In [8]:
tdf = pd.read_csv("Test.csv",header=1 ,index_col="index")
tdf.head()

       cgpa   iq  placement
index
1       5.9  106          0
2       5.3  121          0
3       7.4  132          1
4       5.8  142          0
5       7.1   48          1

# use_cols parameter

In [9]:
df = pd.read_csv("placement.csv")
df.head(2)

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0

In [10]:
df = pd.read_csv("placement.csv",usecols=["iq","placement"])
df

       iq  placement
0   123.0          1
1   106.0          0
2   121.0          0
3   132.0          1
4   142.0          0
..    ...        ...
95  200.0          0
96   42.0          0
97  182.0          1
98  103.0          1
99  113.0          1

[100 rows x 2 columns]

# Squeeze parameter
Read the column as a DataFrame, then convert it to a Series:

In [11]:
df = pd.read_csv("placement.csv", usecols=["iq"]).squeeze("columns")
df

0     123.0
1     106.0
2     121.0
3     132.0
4     142.0
      ...
95    200.0
96     42.0
97    182.0
98    103.0
99    113.0
Name: iq, Length: 100, dtype: float64

# Skiprows/nrows Parameter
skiprows skip the amount of rows given

In [12]:
df = pd.read_csv(
    "placement.csv",
    skiprows=[0, 2],
    names=["cgpa", "iq", "placement"]
)
df

    cgpa     iq  placement
0    6.8  123.0          1
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
5    7.1   48.0          1
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[99 rows x 3 columns]

# nrows is use to take particular number of rows

In [13]:
df = pd.read_csv(
    "placement.csv",
    nrows=50,
    names=["cgpa", "iq", "placement"]
)
df.head()

     cgpa     iq  placement
NaN  cgpa     iq  placement
0.0   6.8  123.0          1
1.0   5.9  106.0          0
2.0   5.3  121.0          0
3.0   7.4  132.0          1

# Encoding parameter

If our data is not encoded in a utf=8 then we should check in which format it is encoded then write 
- pd.read_csv("filename.csv" , encoded = "Format name in which our data is")
### Example
- pd.read_csv("zomato.csv" , encoded = "ladtin-1")

# ------------ Skip Bad ines ----------

In [14]:

df = pd.read_csv("students_bad.csv", on_bad_lines="skip")
df

   id   name   age department   salary
0   1    Ali  25.0         IT  50000.0
1   2  Ahmed  27.0         HR  45000.0
2   3   Sara  26.0    Finance  60000.0
3   5  Usman  24.0      Sales  48000.0
4   6   Zain   NaN        NaN      NaN
5   7   Hina  29.0  Marketing  55000.0
6   8  Bilal  30.0    Finance  62000.0
7  10  Hamza  26.0         IT  53000.0

In [15]:

df = pd.read_csv("students_bad.csv", on_bad_lines="warn")
df

C:\Users\zaina\AppData\Local\Temp\ipykernel_19916\284917737.py:1: ParserWarning: Skipping line 5: expected 5 fields, saw 6
Skipping line 10: expected 5 fields, saw 7

  df = pd.read_csv("students_bad.csv", on_bad_lines="warn")

   id   name   age department   salary
0   1    Ali  25.0         IT  50000.0
1   2  Ahmed  27.0         HR  45000.0
2   3   Sara  26.0    Finance  60000.0
3   5  Usman  24.0      Sales  48000.0
4   6   Zain   NaN        NaN      NaN
5   7   Hina  29.0  Marketing  55000.0
6   8  Bilal  30.0    Finance  62000.0
7  10  Hamza  26.0         IT  53000.0

# dtypes parameter

In [16]:
df = pd.read_csv("placement.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  100 non-null    int64
 1   cgpa        100 non-null    float64
 2   iq          100 non-null    float64
 3   placement   100 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 3.3 KB

In [17]:
pd.read_csv("placement.csv",dtype={"iq": int}).info() # Changed the dtype of iq float to int

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  100 non-null    int64
 1   cgpa        100 non-null    float64
 2   iq          100 non-null    int64
 3   placement   100 non-null    int64
dtypes: float64(1), int64(3)
memory usage: 3.3 KB

# handling dates

In [18]:
pd.read_csv("ipl-matches.csv").info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 148.6 KB

In [19]:
pd.read_csv("ipl-matches.csv",parse_dates=["Date"]).info() # Changed the format of dare into datetime64

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    datetime64[us]
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: datetime64[us](1), float64(1), int64(1), str(17)
memory usage: 148.6 KB

# Convertors

In [20]:
def rename (name):
    if name == "Royal Challengers Bangalore" :
        return "RCB"
    else:
        return name

In [21]:
rename("Royal Challengers Bangalore")

'RCB'

In [22]:
pd.read_csv("ipl-matches.csv",converters={"Team1":rename}) # Change the name in team 1 Royal Challengers Bangalore to RCB

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,RCB,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,RCB,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,RCB,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

# na_values parameter

In [23]:
df = pd.read_csv("Test.csv", na_values=["0","1"]) # na_values is use to tell which value we consider as Null
df

   Unnamed Unnamed2 Unnamed3   Unnamed4
0    index     cgpa       iq  placement
1      NaN      5.9      106        NaN
2        2      5.3      121        NaN
3        3      7.4      132        NaN
4        4      5.8      142        NaN
..     ...      ...      ...        ...
95      95      4.3      200        NaN
96      96      4.4       42        NaN
97      97      6.7      182        NaN
98      98      6.3      103        NaN
99      99      6.2      113        NaN

[100 rows x 4 columns]

# Loading huge datasets into chunks

In [24]:
pd.read_csv("ipl-matches.csv") # orignal

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [25]:
dfs = pd.read_csv("ipl-matches.csv" , chunksize=200)

# Use loops to handle with Chunks

In [26]:
for chunks in dfs:
    print(chunks.shape)

(200, 20)
(200, 20)
(200, 20)
(200, 20)
(150, 20)