In [30]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch','Survived']]
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [31]:
df.dropna(inplace=True)

In [32]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [33]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [34]:
cross_val_score(LogisticRegression(),x,y, scoring='accuracy' , cv =20).mean()

np.float64(0.6933333333333332)

# Applying Feature Constraction

In [35]:
x['Family_type'] = x['SibSp'] + x['Parch'] +1

In [36]:
x

      Age  Pclass  SibSp  Parch  Family_type
0    22.0       3      1      0            2
1    38.0       1      1      0            2
2    26.0       3      0      0            1
3    35.0       1      1      0            2
4    35.0       3      0      0            1
..    ...     ...    ...    ...          ...
885  39.0       3      0      5            6
886  27.0       2      0      0            1
887  19.0       1      0      0            1
889  26.0       1      0      0            1
890  32.0       3      0      0            1

[714 rows x 5 columns]

In [37]:
def myfunc (num):
    if num == 1 :
        return 0 
    if num > 1 & num <=4 :
        return 1
    else:
        return 2

In [38]:
x['Family_type'] = x['Family_type'].apply(myfunc)

In [39]:
x = x.drop(columns= ['SibSp' , 'Parch'])

In [40]:
x

      Age  Pclass  Family_type
0    22.0       3            1
1    38.0       1            1
2    26.0       3            0
3    35.0       1            1
4    35.0       3            0
..    ...     ...          ...
885  39.0       3            1
886  27.0       2            0
887  19.0       1            0
889  26.0       1            0
890  32.0       3            0

[714 rows x 3 columns]

In [41]:
cross_val_score(LogisticRegression() , x,y , scoring='accuracy' , cv = 20) .mean()

np.float64(0.7172619047619048)