In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import lxml

In [2]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko)'}
Webpage = requests.get('https://books.toscrape.com/catalogue/page-1.html',headers=headers).text

In [3]:
soup = BeautifulSoup(Webpage,'lxml') #html parsel

In [4]:
print(soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:30" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="../static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="../static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="../static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="../index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="../index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="../media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="../media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">
             The Coming Woman: A ...

In [5]:
soup.find_all('h3')[0].text # how to extrct one

'A Light in the ...'

In [6]:
len(soup.find_all('h3'))

20

In [7]:
for i in soup.find_all('h3'):
    print(i.text.strip()) #strip is use to remove special character

A Light in the ...
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History ...
The Requiem Red
The Dirty Little Secrets ...
The Coming Woman: A ...
The Boys in the ...
The Black Maria
Starving Hearts (Triangular Trade ...
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little ...
Rip it Up and ...
Our Band Could Be ...
Olio
Mesaerion: The Best Science ...
Libertarianism for Beginners
It's Only the Himalayas

In [8]:
for i in soup.find_all('p', class_='price_color'):
    price_clean = i.text.replace("Â£","£") 
    print(price_clean.strip())

£51.77
£53.74
£50.10
£47.82
£54.23
£22.65
£33.34
£17.93
£22.60
£52.15
£13.99
£20.66
£17.46
£52.29
£35.02
£57.25
£23.88
£37.59
£51.33
£45.17

In [9]:
for i in soup.find_all('p', class_="instock availability"):
    print(i.text.strip())

In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock
In stock

In [10]:
books = soup.find_all('article',class_="product_pod")

In [11]:
len(books)

20

In [12]:
Book_Name = []
Price = []
Star_rating=[]
Available = []

for i in books:
    Book_Name.append(i.find('h3').text.strip())

    clean_p = i.find('p',class_="price_color").text.replace("Â£","£")
    Price.append(clean_p.strip())

    Available.append(i.find('p',class_='instock availability').text.strip())

    rating_tag = i.find('p',class_='star-rating')
    Star_rating.append(rating_tag['class'][1])

d = {"Book_Name":Book_Name ,"Star_rating":Star_rating , "Price":Price , "Availablity": Available}

df = pd.DataFrame(d)

In [13]:
df.head()

                      Book_Name Star_rating   Price Availablity
0            A Light in the ...       Three  £51.77    In stock
1            Tipping the Velvet         One  £53.74    In stock
2                    Soumission         One  £50.10    In stock
3                 Sharp Objects        Four  £47.82    In stock
4  Sapiens: A Brief History ...        Five  £54.23    In stock

In [14]:
df.shape

(20, 4)

In [15]:
final = pd.DataFrame()

for j in range(1,51):

    url = 'https://books.toscrape.com/catalogue/page-{}.html'.format(j)
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko)'}
    Webpage = requests.get(url,headers=headers).text
    soup = BeautifulSoup(Webpage,'lxml') 
    books = soup.find_all('article',class_="product_pod")

    Book_Name = []
    Price = []
    Star_rating=[]
    Available = []

    for i in books:
        Book_Name.append(i.find('h3').text.strip())

        clean_p = i.find('p',class_="price_color").text.replace("Â£","£")
        Price.append(clean_p.strip())

        Available.append(i.find('p',class_='instock availability').text.strip())

        rating_tag = i.find('p',class_='star-rating')
        Star_rating.append(rating_tag['class'][1])

    d = {"Book_Name":Book_Name ,"Star_rating":Star_rating , "Price":Price , "Availablity": Available}

    df = pd.DataFrame(d)

    final = pd.concat([final,df],ignore_index=True)

In [16]:
final

                            Book_Name Star_rating   Price Availablity
0                  A Light in the ...       Three  £51.77    In stock
1                  Tipping the Velvet         One  £53.74    In stock
2                          Soumission         One  £50.10    In stock
3                       Sharp Objects        Four  £47.82    In stock
4        Sapiens: A Brief History ...        Five  £54.23    In stock
..                                ...         ...     ...         ...
995  Alice in Wonderland (Alice's ...         One  £55.53    In stock
996    Ajin: Demi-Human, Volume 1 ...        Four  £57.06    In stock
997         A Spy's Devotion (The ...        Five  £16.97    In stock
998           1st to Die (Women's ...         One  £53.98    In stock
999           1,000 Places to See ...        Five  £26.08    In stock

[1000 rows x 4 columns]

In [19]:
final[final['Price'] == '£26.08']

                   Book_Name Star_rating   Price Availablity
999  1,000 Places to See ...        Five  £26.08    In stock

In [21]:
final.to_csv('Books Inventory Dataset.csv',index=False)