In [168]:
import pandas as pd
import numpy as np

In [169]:
time = pd.read_csv('messages.csv',usecols= ['date'])
date =  pd.read_csv('orders.csv',usecols=['date'])

In [170]:
time.head()

                  date
0  2013-12-15 00:50:00
1  2014-04-29 23:40:00
2  2012-12-30 00:21:00
3  2014-11-28 00:31:00
4  2013-10-26 23:11:00

In [171]:
date.head()

         date
0  2019-12-10
1  2018-08-15
2  2018-10-23
3  2019-08-17
4  2019-01-06

In [172]:
date.info() # by default in pandas df date time is object change its type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [173]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [174]:
date['date'] = pd.to_datetime(date['date'])

In [175]:
date['date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: date
Non-Null Count  Dtype
--------------  -----
1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

In [176]:
# Extracting year

date['year'] = date['date'].dt.year #dt = datetime

In [177]:
# extracting mont

date['Month'] = date['date'].dt.month

In [178]:
# extracting month name

date['month_name'] = date['date'].dt.month_name()

In [179]:
# extracting days 

date['days'] = date['date'].dt.day

In [180]:
date['day_name'] = date['date'].dt.day_name()

In [181]:
# day of week
date['day_of_week'] = date['date'].dt.day_of_week

In [182]:
# day_of_year

date['day_of_year'] = date['date'].dt.day_of_week

In [183]:
date['Weekend'] = np.where(date['day_name'].isin(['Sunday' , 'Saturday']),1,0)

In [184]:
date['Week_of_year'] = date['date'].dt.isocalendar().week

In [185]:
date['Quater'] = date['date'].dt.quarter

In [186]:
date['Semester'] = np.where(date['Quater'].isin([1,2]) , 1 ,2)

# extract time elapsed betweem dates

In [187]:
import datetime

todays = datetime.datetime.today()
todays

datetime.datetime(2026, 8, 19, 16, 17, 48, 288113)

In [188]:
todays - date['date']

0     2444 days 16:17:48.288113
1     2926 days 16:17:48.288113
2     2857 days 16:17:48.288113
3     2559 days 16:17:48.288113
4     2782 days 16:17:48.288113
                 ...
995   2872 days 16:17:48.288113
996   2813 days 16:17:48.288113
997   2661 days 16:17:48.288113
998   2726 days 16:17:48.288113
999   2500 days 16:17:48.288113
Name: date, Length: 1000, dtype: timedelta64[ns]

In [189]:
# passed days

(todays - date['date']).dt.days

0      2444
1      2926
2      2857
3      2559
4      2782
       ...
995    2872
996    2813
997    2661
998    2726
999    2500
Name: date, Length: 1000, dtype: int64

In [190]:
# Passed month
(
    (todays.year - date['date'].dt.year) * 12
    + (todays.month - date['date'].dt.month)
)

0      80
1      96
2      94
3      84
4      91
       ..
995    94
996    92
997    87
998    89
999    82
Name: date, Length: 1000, dtype: int32

# **Work with time**

In [191]:
time['date'] = pd.to_datetime(time['date'])

In [192]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

In [193]:
time['Sec'] = time['date'].dt.second
time['Minutes'] = time['date'].dt.minute
time['hours'] = time['date'].dt.hour

time['time'] = time['date'].dt.time

In [194]:
time

                   date  Sec  Minutes  hours      time
0   2013-12-15 00:50:00    0       50      0  00:50:00
1   2014-04-29 23:40:00    0       40     23  23:40:00
2   2012-12-30 00:21:00    0       21      0  00:21:00
3   2014-11-28 00:31:00    0       31      0  00:31:00
4   2013-10-26 23:11:00    0       11     23  23:11:00
..                  ...  ...      ...    ...       ...
995 2012-03-16 00:50:00    0       50      0  00:50:00
996 2014-01-23 23:14:00    0       14     23  23:14:00
997 2012-10-15 23:37:00    0       37     23  23:37:00
998 2012-06-21 23:34:00    0       34     23  23:34:00
999 2014-06-19 23:25:00    0       25     23  23:25:00

[1000 rows x 5 columns]

# **Time Difference**

In [195]:
todays - time['date']

0     4630 days 15:27:48.288113
1     4494 days 16:37:48.288113
2     4980 days 15:56:48.288113
3     4282 days 15:46:48.288113
4     4679 days 17:06:48.288113
                 ...
995   5269 days 15:27:48.288113
996   4590 days 17:03:48.288113
997   5055 days 16:40:48.288113
998   5171 days 16:43:48.288113
999   4443 days 16:52:48.288113
Name: date, Length: 1000, dtype: timedelta64[ns]

In [196]:
# in sec

(todays - time['date'] ) / np.timedelta64(1 , 's')

0      4.000877e+08
1      3.883415e+08
2      4.303294e+08
3      3.700216e+08
4      4.043272e+08
           ...
995    4.552973e+08
996    3.966374e+08
997    4.368120e+08
998    4.468346e+08
999    3.839360e+08
Name: date, Length: 1000, dtype: float64

In [ ]:

(todays - time['date'] ) / np.timedelta64(1 , 'm')  # m for minuts

0      6.668128e+06
1      6.472358e+06
2      7.172157e+06
3      6.167027e+06
4      6.738787e+06
           ...
995    7.588288e+06
996    6.610624e+06
997    7.280201e+06
998    7.447244e+06
999    6.398933e+06
Name: date, Length: 1000, dtype: float64

In [198]:

(todays - time['date'] ) / np.timedelta64(1 , 'h')  # h for hours

0      111135.463413
1      107872.630080
2      119535.946747
3      102783.780080
4      112313.113413
           ...
995    126471.463413
996    110177.063413
997    121336.680080
998    124120.730080
999    106648.880080
Name: date, Length: 1000, dtype: float64