In [18]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score

In [19]:
df = pd.read_csv('train.csv',usecols=['Age' , 'Fare','SibSp' ,'Parch',"Survived"])

In [20]:
df['family'] = df['SibSp']+df['Parch']

In [21]:
df.head()

   Survived   Age  SibSp  Parch     Fare  family
0         0  22.0      1      0   7.2500       1
1         1  38.0      1      0  71.2833       1
2         1  26.0      0      0   7.9250       0
3         1  35.0      1      0  53.1000       1
4         0  35.0      0      0   8.0500       0

In [22]:
df = df.drop(columns=['SibSp','Parch'])

In [23]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

x_train

      Age      Fare  family
331  45.5   28.5000       0
733  23.0   13.0000       0
382  32.0    7.9250       0
704  26.0    7.8542       1
813   6.0   31.2750       6
..    ...       ...     ...
106  21.0    7.6500       0
270   NaN   31.0000       0
860  41.0   14.1083       2
435  14.0  120.0000       3
102  21.0   77.2875       1

[712 rows x 3 columns]

In [25]:
# Without binarization

clf = DecisionTreeClassifier()

clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

print(accuracy_score(y_test,y_pred))

0.6536312849162011

In [26]:
cross_val_score(clf,x,y,scoring='accuracy',cv=10).mean()

np.float64(0.6498127340823969)

# Binarization

In [27]:
from sklearn.preprocessing import Binarizer

In [28]:
trf = ColumnTransformer([
    ('binarize' , Binarizer(copy=False),['family'])
],remainder='passthrough')

In [29]:
x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

In [31]:
pd.DataFrame(x_train_trf,columns=['family' , 'Age' , 'Fare'])

     family   Age      Fare
0       0.0  45.5   28.5000
1       0.0  23.0   13.0000
2       0.0  32.0    7.9250
3       1.0  26.0    7.8542
4       1.0   6.0   31.2750
..      ...   ...       ...
707     0.0  21.0    7.6500
708     0.0   NaN   31.0000
709     1.0  41.0   14.1083
710     1.0  14.0  120.0000
711     1.0  21.0   77.2875

[712 rows x 3 columns]

In [32]:
# Without binarization

clf = DecisionTreeClassifier()

clf.fit(x_train_trf,y_train)

y_pred3 = clf.predict(x_test_trf)

print(accuracy_score(y_test,y_pred3))

0.6201117318435754

In [36]:
x_trfx = trf.fit_transform(x)
cross_val_score(clf,x_trfx,y,scoring='accuracy' , cv=10).mean()

np.float64(0.6520973782771535)