In [593]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [594]:
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [595]:
df_cop = df[['R&D Spend','Administration','Marketing Spend']].copy()

In [596]:
df.iloc[3,1] # 3 for row and 1 for value

np.float64(16.0)

In [597]:
df_cop.iloc[1,0] = np.nan
df_cop.iloc[3,1] = np.nan
df_cop.iloc[-1,-1] = np.nan
df_cop.head()

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

# **Step1 impute all values with mean of that col**

In [598]:
df0 = pd.DataFrame()

df0['R&D Spend'] =df_cop['R&D Spend'].fillna(df_cop['R&D Spend'].mean())
df0['Administration'] = df_cop['Administration'].fillna(df_cop['Administration'].mean())
df0['Marketing Spend'] = df_cop['Marketing Spend'].fillna(df_cop['Marketing Spend'].mean())

# **Remove the col2 imputed value**

In [599]:
df1 = df0.copy()
df1.iloc[1,0] = np.nan
df1

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [600]:
# Use first 3 rows to build a model and use the last for prediction

x = df1.iloc[[0,2,3,4],1:]
y = df1.iloc[[0,2,3,4],0]

In [601]:
lr = LinearRegression()

lr.fit(x,y)

lr.predict(df1.iloc[1,1:].values.reshape(1,2))

c:\Users\zaina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.14158651])

In [602]:
df1.iloc[1,0] = 23.14

In [603]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      23.14             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            29.25

In [604]:
x = df1.iloc[[0,1,2,4] , [0,2]]
y = df1.iloc[[0,1,2,4],1]

In [605]:
df1.iloc[3,[0,2]]

R&D Spend          12.0
Marketing Spend    26.0
Name: 14, dtype: float64

In [606]:
lr.fit(x,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

c:\Users\zaina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.06331285])

In [607]:
df1.iloc[3 , 1] = 11.06

In [608]:
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            29.25

# **Remove the col3 imputed value**

In [609]:
df1.iloc[4, 2] = np.nan
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00             30.0
37      23.14            5.00             20.0
2       15.00           10.00             41.0
14      12.00           11.06             26.0
44       2.00           15.00              NaN

In [610]:
x = df1.iloc[0:4,0:2 ] 
y = df1.iloc[0:4,-1]
x

    R&D Spend  Administration
21       8.00           15.00
37      23.14            5.00
2       15.00           10.00
14      12.00           11.06

In [611]:
lr = LinearRegression()
lr.fit(x,y)
lr.predict(df1.iloc[4,0:2] .values.reshape(1,2))

c:\Users\zaina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([31.56351448])

In [612]:
df1.iloc[4 , -1] = 31.56

In [613]:
df1-df0

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37      13.89            0.00             0.00
2        0.00            0.00             0.00
14       0.00           -0.19             0.00
44       0.00            0.00             2.31

# 2nd iteration

In [614]:
df2 = df1.copy()
df2.iloc[1,0] = np.nan
df2.head()

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.06            26.00
44        2.0           15.00            31.56

In [615]:
x = df2.iloc[[0,2,3,4,] , 1:3]
y = df2.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [616]:
lr.fit(x,y)
lr.predict(df2.iloc[1 , 1:3 ].values.reshape(1,2))

c:\Users\zaina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([23.78627207])

In [617]:
df2.iloc[1,0] = 23.78

In [618]:
df2

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            31.56

In [619]:
df2.iloc[3,1] = np.nan
x = df2.iloc[[0,1,2,4],[0,2]]
y =  df2.iloc[[0,1,2,4],1]

lr.fit(x,y)
lr.predict(df.iloc[3 ,[0,2]].values.reshape(1,2))

c:\Users\zaina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.22020174])

In [620]:
df2.iloc[3,1] = 11.22

In [621]:
df2.iloc[4,-1] = np.nan
x = df2.iloc[0:4 , 0:2]
y = df2.iloc[0:4 , -1]

In [622]:
df2

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00             30.0
37      23.78            5.00             20.0
2       15.00           10.00             41.0
14      12.00           11.22             26.0
44       2.00           15.00              NaN

In [623]:
lr.fit(x,y)

lr.predict(df2.iloc[4 , 0:2].values.reshape(1,2))

c:\Users\zaina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([38.87979054])

In [624]:
df2.iloc[4 , -1] = 38.87

In [625]:
df2-df1

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37       0.64            0.00             0.00
2        0.00            0.00             0.00
14       0.00            0.16             0.00
44       0.00            0.00             7.31

In [626]:
df2

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.22            26.00
44       2.00           15.00            38.87

# 3rd iteration

In [627]:
df3 = df2.copy()

In [628]:
df3.iloc[1,0] = np.nan
x = df3.iloc[[0,2,3,4] , 1:3]
y = df3.iloc[[0,2,3,4] , 0]

lr.fit(x,y)

LinearRegression()

In [629]:
lr.predict(df3.iloc[1 , 1:].values.reshape(1,2))

c:\Users\zaina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([26.82082209])

In [630]:
df3.iloc[1,0] = 13.45

In [631]:
df3.iloc[3,1] = np.nan

x = df3.iloc[[0,1,2,4] , [0,2]]
y =  df3.iloc[[0,1,2,4] ,1]

lr.fit(x,y)

LinearRegression()

In [632]:
lr.predict(df3.iloc[3 , [0,2]].values.reshape(1,2))

c:\Users\zaina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([8.63432316])

In [633]:
df3.iloc[3,1] = 8.63

In [634]:
df3.iloc[4,-1] = np.nan
x = df3.iloc[0:4 , 0:2]
y = df3.iloc[0:4 , -1]

lr.fit(x,y)

LinearRegression()

In [635]:
lr.predict(df3.iloc[4 , 0:2].values.reshape(1,2))

c:\Users\zaina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([7.7467838])

In [636]:
df3.iloc[4,-1] = 7.74

In [637]:
df3 - df2

    R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37     -10.33            0.00             0.00
2        0.00            0.00             0.00
14       0.00           -2.59             0.00
44       0.00            0.00           -31.13